[#g3,reftext=G.3]
=== (G.3) Expected Benefits
The primary benefit of this project is to provide a cost-effective and user-friendly voxel-based design tool that converts CAD models into voxel grids, enabling flexible editing and material property assignment. This solution reduces design time and supports the department’s research in multi-material 3D printing.

For researchers and students, the tool will streamline workflows by allowing faster iteration and enabling edits or re-magnetization of voxel properties without rebuilding models from scratch.

For supervisors and the university, the system offers a more user-friendly and productive platform, allowing larger CAD models to be automatically voxelized and then edited efficiently. This makes complex designs more manageable and accelerates experimental research.

The following goal model diagram illustrates how these benefits map to the project’s stakeholders.
image::models/G3_uml.svg[scale=70%,align="center"]
ifdef::env-draft[]
TIP: _New processes, or improvement to existing processes, made possible by the project's results. It presents the business benefits expected from the successful execution of the project. **This chapter is the core of the Goals book**, describing what the organization expects from the system. It ensures that the project remains focused: if at some stage it gets pushed in different directions, with “creeping featurism” threatening its integrity, a reminder about the original business goals stated in those chapters will help._  <<BM22>>
endif::[]

{emptysec}
