[#e1,reftext=E.1]
=== (E.1) Glossary

ifdef::env-draft[]
TIP: _Clear and precise definitions of all the vocabulary specific to the application domain, including technical terms, words from ordinary language used in a special meaning, and acronyms. It introduces the terminology of the project; not just of the environment in the strict sense, but of all its parts._  <<BM22>>
endif::[]

This section details all technical terms used throughout this project's documentation, as well as project-specific vocabulary (eg. words used in different contexts here) and any non-obvious acronyms.

*3D* 

Three-dimensional; in the context of this project, 3D implies the image produced evokes depth. In the case of voxels or vectors, 3D implies three spatial dimensions.

*3D Mesh*

Alternative way of referring to the 3D model contained within a CAD file; these files often store these models as collections of vertices, colloquially referred to as a mesh.

*3D Model*

A collection of vertices in 3D space, connected via edges and faces. A given CAD file contains these models in some fashion.

*CAD File*

A file containing a 3D model, generated by CAD (Computer Aided Design) software. In the context of this project, these are files the system can take as input in order to output a project file, containing a voxel model equivalent of the original 3D model.

*CAD Software*

Software used to create and modify 3D models and designs, stored as CAD files.

*Custom 3D Printer Software*

The software used by Researchers/Lab Operators that controls the custom 3D printer. This software takes the files the system exports (printer-ready files) as input.

*Display Section*

A portion of the voxel model that is displayed at a time. For large models, the model is broken down into parts; only one is displayed at a time. This is done to save computer resources.

*Export File / Printer-ready File / Metadata File*

A file generated from a project file, containing all data related to each voxel (coordinates, material assignment, magnetization). 

*Grid*

The workspace a voxel model exists within (eg. a coordinate system). Voxels align to a cartesian coordinate system, voxels can be created within it.

*Magnetization vector*

A 3D polar coordinate the user enters to specify the magnitude and direction of the magnetic field within an individual voxel. Also referred to as a magnetization. See more about magnetic field theory link:https://www.britannica.com/science/magnetic-field[here] <<BR25,[4]>>.

*Material ID*

A non-negative whole number that represents the material of an individual voxel. Users can link a color and name to these IDs. Also referred to as a material assignment.

*Model Slicing / Voxelization*

The process by which an input CAD file is converted to a voxel model / project file. The name results from the analogy of "cutting" a 3D model into cubes.

*Project File*

A file that contains the data related to a voxel model, as well as other saved data the system stores with a project (eg. display sections).

*Voxel*

Traditionally, a voxel is the equivalent of a 3D pixel - values aligning to a regular 3D grid that takes on the appearance of a cube. Within our project, it is possible for the height of these voxels to change.

*Voxel model*

A collection of voxels that the user can manipulate, assigning each voxel properties or adding/removing voxels. 
