[#e3,reftext=E.3]
=== (E.3) Constraints

ifdef::env-draft[]
TIP: _Obligations and limits imposed on the project and system by the environment. This chapter defines non-negotiable restrictions coming from the environment (business rules, physical laws, engineering decisions), which the development will have to take into account._  <<BM22>>
endif::[]

* *Operating System Support.* The system must support the Linux operating system. This constraint is necessary to ensure the application can be installed and run on the lab computers utilised by the application's users.

* *STL File Support.* To support the importing and converting of user-created external CAD files, the system must parse STL files.  

* *Java File Support.* In order to export user-created voxel compositions in a format usable by pre-existing 3D printing software, the system must support the creation of java-readable files containing all necessary metadata.

* *Minimize resource usage.* The system must be implemented in such a way to minimise the usage of computer resources as much as is feasible. Some level of usage is unavoidable; a main feature of the system is the rendering of a 3D graphical user interface. However, it is important to balance needed functionality and device resource usage. Desktop resources are limited, and may be utilised for other tasks simultaneously.  

