[#e4,reftext=E.4]
=== (E.4) Assumptions

ifdef::env-draft[]
TIP: _Properties of the environment that may be assumed, with the goal of facilitating the project and simplifying the system. It defines properties that are not imposed by the environment (like those in <<e3>>) but assumed to hold, as an explicit decision meant to facilitate the system's construction._  <<BM22>>
endif::[]

This section details any assumptions made that are not imposed upon the project. As follows are assumptions made to simplify project scope.

* *Operating System Support:* We assume that only recent Windows releases and Linux distributions that are made use of by primary users will need to be supported. For the first development iteration, this is sufficient to satisfy all potential users.

* *Processing Power:* We assume that the lab computers possess at least the resources required to handle rudimentary 3D graphics. 

* *Browser Support:* We assume that the system will only support Chromium browsers. This will capture a majority of the most popular browsers in use.

* *Language Support:* We assume that the only language the system supports will be English. This captures the needs of the primary users.