[#e5,reftext=E.5]
=== (E.5) Effects

ifdef::env-draft[]
TIP: _Elements and properties of the environment that the system will affect. It defines effects of the system's operations on properties of the environment. Where the previous two categories (<<e3>>, <<e4>>) defined influences of the environment on the system, effects are influences in the reverse direction._  <<BM22>>
endif::[]

This section details the most important effects of the system; we focus on the benefits usage of the system provides to stakeholders.

* *Increased productivity of users.* A key pain point expressed by primary users is the extensive time spent tediously creating models voxel-by-voxel from paper sketches. With our system in place automating conversion from CAD files, users will be able to spend this time on other projects, alleviating hours of menial work from their schedule. In addition, the dedicated, lightweight property assignment interface will speed up time to assign material IDs and magnetic vectors to voxel models versus the general-purpose physics simulation software currently employed by primary users.

* *Increased lab output.* With primary users more productive, model ideas can be actualised and tested more quickly. Users will no longer need to budget time to convert models to voxels, and can instead develop new ideas. With multiple instances of the system, many models can be worked on in parallel, further increasing output. Finally, with the aid of the system, the production of more complicated models becomes more feasible, freed from time constraints.
