[#rf,reftext=RF]

=== (RF) Reflections

*1. What went well while writing this deliverable?*

Overall, the deliverable progressed smoothly after the development of the problem statement and goals. The peer feedback we received kept us on our toes, ensuring we remained focused on delivering a document that not only followed the rubric but captured our client's needs succintly. Our plan was straightforward; create an initial draft of the SRS, verify any assumptions made during a client meeting, verify our writing style with the TA, and make necessary corrections. This plan was executed successfully, with the client meeting being extremely useful and resulting in numerous changes to project scope (the most prominent addition being material assignments to voxels). Despite the tense deadlines, the group succeeded in completing their pieces with time for review.

*2. What pain points did you experience during this deliverable, and how did you resolve them?*

_Omar_

_Daniel_

An issue I personally encountered was challenges with ensuring document consistency in naming, numbering, style, and how concepts are explained. In order to balance our individual workloads and work on the document, we split up work and went our own ways. This was fine; however it led to inevitable inconsistencies between sections. As the primary reviewer of all sections, I was in charge of catching these. Deciding upon standards was tricky at times, especially when one section references another (e.g. a scenario implying the existence of functional requirements we didn't have). Client meetings were able to clear up most serious disagreements, leaving primarily naming and numbering errors, which were easier to deal with.

_Andrew_

_Olivia_

Prior to creating the requirements section of the document, we did have meetings with stakeholders so they could share their experience and the challenges they currently face. However, I still struggled with creating requirements that would sufficiently cover user needs that were not explicitly stated but would be essential. I found that without first-hand experience, intuitive understanding of the unspoken user needs was limited. To address this issue, I made a first draft of requirements that incorporated assumed user needs. During a subsequent meeting with Dr. Onaizah, I was able to get feedback based on her first-hand experience in direct relation to the scope of each requirement. This provided insight on the value and impact of each requirement, which helped guide future revisions. It definitely strengthened my confidence that the final requirements list is comprehensive and reflective of what the system requires.

_Khalid_: 

The challenge that I faced when working with this deliverable is keeping the consistency between the requirements and the detailed usage scenarios. This was particularly difficult because the requirements were frequently evolving, which meant I had to constantly update the usage scenarios to reflect the latest changes. Another challenge was the misunderstanding between the group and the supervisor, as we missed an important requirement of adding and removing voxels, which was cleared up during the meetings.

*3. How many of your requirements were inspired by speaking to your client(s) or their proxies (e.g. your peers, stakeholders, potential users)?*

A large majority of requirements were directly from our talks with Dr. Onaizah, with additional requirements from our own ideas of what may facilitate their work or standard editing software. For instance, the ability to edit each layer individually became viewing it separately; editing voxel properties individually became the panels to edit these properties of selected voxels. Standard editing requirements included undo/redo functionality (not explicitly stated by stakeholders, but a reasonable assumption), the ability to save as/autosave, etc. Usability requirements surfaced from both difficulties discussed about their current solution, as well as our own preferences when editing files (another reasonable set of preferences, given we have all done similar technical work). Ultimately, when requirements came from our conceptions of what the product should be like, cross-checking with our client was top priority; we still retain plans to verify the finer details of this document with Dr. Onaizah as part of our verification plan.

*4. Which of the courses you have taken, or are currently taken, will help your team to be successful with your capstone project?*

_Omar_

_Daniel_

* *SFWRENG 3A04* - Large scale system design knowledge will come in handy when developing the overall structure for both the POC and revisions. Code maintainability will be absolutely essential both while working on the project ourselves, and if the project is to be maintained/expanded upon in the future by other people.

* *SFWRENG 3DB3* - Skills in SQL, as well as database management, will be useful when developing the user edit history module.

* *SFWRENG 4X03* - When working on the 3D rendering modules, knowledge of scientific computation (both how to accomplish things efficiently and avoiding error) will be useful, given the large amount of computation required.

* *SFWRENG 2AA4* - Code design on smaller scales will further ensure code written is maintainable and logical to future people who may work on the project.

_Andrew_

_Olivia_

* *SFWRENG 3RA3:* This course provided foundational knowledge and theoretical practice in developing an SRS document. That experience served as a significant guide, majorly influencing the development of our current SRS document.

* *SFWRENG 3DB3:* Due to the large amounts of expected data, the significant time complexity of data manipulation exceeds the capabilities of most data structures. Therefore, we will likely have to integrate a database to support any operation that accesses a specific voxel and its related metadata. The teachings from this course allow us to understand how databases work to effectively use them within our system.

* *SFWRENG 3BB4 & SFWRENG 3SH3:* The teachings from these two courses may help optimize implementation methods during import and export processes. Between both courses, I feel that I have built a fairly comprehensive understanding of threads, concurrency, synchronization and resource handling. I believe that this information could be used to improve the performance of our import and export process by effectively leveraging the capabilities of parallel computation.

* *SFWRENG 3S03:* It is essential that the system we are building is robust and well-tested, as it is being developed for actual implementation and usage after the Capstone is complete. The teachings from this course will help guide the development of a comprehensive testing plan that can build confidence in the reliability of our system when we are no longer around to help fix any bugs.

_Khalid_

* *SFWRENG 3A04* - This is a large system design course, that helped a lot when working on the overall system architecture and ensuring the project's maintainability.

* *SFWRENG 3RA3* - This is a software requirements and safety considerations course, this helped me a lot when I was creating the detailed usage scenarios, as it provided a structured approach to defining user needs and system behaviors.

* *SFWRENG 4HC3* - This is a human computer interfaces course, this helped a lot when thinking about how the system interface would look like, what kind of considerations that need to be taken like Feedback, Mappings, and Constraints, which are essential for an intuitive user experience.

*5. What knowledge and skills will the team collectively need to acquire to succesfully complete this capstone project? Examples of possible knowledge to acquire include domain specific knowledge from the domain of your application, or software engineering knowledge, mechatronics knowledge, or computer science knowledge. Skills may be related to technology, or writing, or presentation, or team management, etc. You should look to identify at least one item for each team member.*

There are five major knowledges/skills our group will need:

* _Knowledge of 3D rendering technologies,_ notably how to ensure performance is acceptable. This will be intrinsically linked to which library is utilised.

* _Knowledge of STL file specifications._ This arises specifically from the constraint on input files to the system; knowledge of their format, how to validate and modify them will be essential.

* _Knowledge of the custom 3D printer software._ While we will not be working with it directly, knowledge of how it expects to take input and how it can fail will be extremely useful assets when developing the export modules.

* _Developing intuitive user interfaces._ Despite there being many examples of good interfaces we can use as reference or inspiration, this skill will still be necessary both when creating the more custom parts of the interface, and when discussing with stakeholders what would work best for them (e.g. drawing out tacit knowledge).

* _Conflict resolution._ Over the coming seven months, it is highly unlikely no conflicts between team members will arise, even minor ones. Being able to facilitate tough conversations and the ability to reduce tension and/or the stakes of a situation is important to maintaining group morale during stressful times.

*6. For each of the knowledge areas and skills identified in the previous question, what are at least two approaches to acquiring the knowledge or mastering the skill? Of the identified approaches, which will each team member pursue, and why did they make this choice?*

_Conflict resolution approaches._

*Active-listening–based problem solving:* This approaches conflict resolution with a focus on effective, open communication. It gives each person a chance to explain their perspective while all remaining parties give their full, undivided attention. While listening to someone else’s perspective, the goal is to understand where the other person is coming from, even if you still disagree. This approach can help foster trust and strengthen group dynamics by ensuring all group members feel valued and heard when determining a solution to the conflict.


*Integrated mediation:* This approach integrates a neutral party to help facilitate effective conversation between the two parties that disagree. It is still the responsibility of the two parties to come together with a final decision they both agree on. The mediator is not responsible for making a final decision that ends the disagreement. Rather, the mediator can help defuse tension and keep the conversation productive, ensuring both parties are able to interact with each other in an equitable and respectful manner. By introducing a mediator, this helps prevent misunderstandings or an imbalance in power.



_Omar_

_Daniel_

Regarding the fourth skill, there are two main avenues ahead of me to mastering the skill:

* *Online research on best style/practices.* There is endless information available online related to developing intuitive, human-centered designs. This type of learning is something I am intimately familiar with from work on both personal projects and to catch up when a course is lacking.

* I (along with other team members) are currently enrolled in a *course focused on human-centered design,* which includes a full project meant to develop this skill. This provides a more structured learning approach, also including collaboration.

I likely will pursue a mix of these approaches given what the project ends up warranting. Online research will supplement any knowledge the course does not provide (e.g. specific guidelines). The timeline of course completion aligns perfectly with when UI will likely be developed, so a majority of skill development will lean on the course.

_Andrew_

_Olivia_

For *knowledge of 3D rendering technologies*, I will pursue documentation for libraries and frameworks because I believe that will be more helpful for learning how to execute 3D rendering. I anticipate that it will be difficult to create a system that supports these visuals within our UI/UX, as it is likely very technical in nature. Learning more about potential libraries and frameworks can allow me to properly leverage their capabilities to tackle this complex problem. I think later experimentation with existing 3D modeling software is good to understand how a UI/UX design effectively supports user interaction with a 3D model.

For *knowledge of STL file specifications*, I will initially pursue online research and documentation review to build the necessary knowledge, as I have no background in working with STL files. This means that to even attempt any practical implementation, I need to build a foundation of theoretical knowledge, which will require online resources. Once I build that theoretical knowledge, I can then leverage hands-on practice with STL file modifications to verify correct understanding.

For *knowledge of the custom 3D printer software*, I will be pursuing interviews with our supervisor, Dr Onaizah. The existing documentation will likely be unnecessarily complex and technical in nature, making it difficult to understand. Dr Onaizah will be able to provide the information we require much more intuitively while avoiding technical details that are irrelevant within our project scope. It is also easier to clarify details or confusion, as you’re able to receive immediate feedback during a conversation.

For *developing intuitive user interfaces*, I will be pursuing the avenue of learning through coursework, as it offers a more thorough understanding of principles and considerations that can be accidentally overlooked during online research. This is especially relevant when you don’t know where to start when looking at online resources. Therefore, emphasizing the integration of course teachings ensures there is a solid design foundation. From there, online resources can help fill any gaps in knowledge that remain.

For *conflict resolution*, I will be pursuing active listening, as I believe it is ideal based on current group dynamics. Personally, my experience has made me feel that my group values my thoughts and perspective. There also haven’t been any moments of high tensions or significant power imbalances that would require a mediator. Even when they disagree, all group members have been respectful and civil. Therefore, if I make the conscious effort to reciprocate that respect and engagement when they share their opinions, I feel that our group is more than capable of having an effective conversation to determine a solution.


_Khalid_

For the second skill, *Knowledge of STL file specifications*, these are the ways that will help me in mastering the skill:

* *Online research and documentation review.* The STL file format is well-documented, there are numerous of online resources and tutorials that details the structure of the file. Most famously *Adobe*, has a well documented page explaining STL file format and how to create one. This approach allows me to understand the STL file specifications theoretically.

* *Practical implementation through parsing and validation.* Working with existing libraries to write a basic parser for STL files will provide me hands-on experience, this will help me understand the structure even more and how I can deal with it practically. This will involve reading, interpreting, and validating the data within STL files.

I will primarily use the practical implementation approach. While theoretical knowledge is important, the system's requirement of validating and modifying STL files is a necessity, and any practical understanding can only be gained from hands-on experience working with the STL files. However, I will use online research and documentation when needed as a reference for specific details and edge cases encountered during implementation.

